package p04.catch_order;

public class CatchOrderEx {

	public static void main(String[] args) {
		String data1 = null;	
		String data2 = null;
		
		try {
			// ArrayIndexOutOfBoundsException 발생
			data1 = args[0];	// args[0] = null
			data2 = args[1];	// args[1] = null
			
			int val1 = Integer.parseInt(data1);		
			int val2 = Integer.parseInt(data2);		// a10
			int result = val1 + val2;
			System.out.println(data1 + " + " + data2 + " = " + result);
			Class cls = Class.forName("java.lang.String");
			// Exception class는 모든 RuntimeException, compile관련 Exception 모두의 부모
			// - promotion 발생
	//	} catch (Exception e) {		// 모든 exception 수행되는 문제 발생 
	//		
		} catch (ArrayIndexOutOfBoundsException e){
			System.out.println("실행 매개변수의 수가 부족합니다.");
			System.out.println("[실행 방법]");
			System.out.println("eclipse Run - Run Configuration 메뉴에 들어가서 num1, num2 입력하세요.");
		} catch (NumberFormatException e) {
			System.out.println("숫자로 변환할 수 없습니다.");
		} catch (ClassNotFoundException e) {
			System.out.println("compile time 관련 exception 에러 처리");
		} finally {
			System.out.println("숫자 덧셈 연산 처리 프로그램이 종료되었습니다.");
		}
	}
}


